# Forge starter — convenience commands. These ONLY delegate to Docker.
# No local Node, npm, or build tools are assumed.

.PHONY: up down logs shell ps restart pull new-app \
        deploy release deploy-ps deploy-logs deploy-config deploy-down

up:
	docker compose up -d
	@echo ""
	@echo "Forge is up. Provision a whole app in one command:"
	@echo "  ./new-app my-app                 # init->provision->install->build->test->lint"
	@echo "Or step by step: ./forge init app --name my-app  (then provision/install/build/…)"
	@echo "Or just tell Claude: \"build me a <thing>\" (see .claude/skills/provision-app)."

# One command to scaffold + validate a new app:  make new-app name=my-app
new-app:
	@test -n "$(name)" || (echo "usage: make new-app name=<kebab-name>"; exit 2)
	./new-app "$(name)"

down:
	docker compose down

logs:
	docker compose logs -f api

shell:
	docker compose exec api sh

ps:
	docker compose ps

restart:
	docker compose restart api

# Refresh the platform image from the registry.
pull:
	docker compose pull

# --- Production deployment (app/compose.prod.yaml — generated by C8) --------
# Runs on the DEPLOY host — the app + Forge data-plane sidecar + Postgres, no
# control plane. Pull-and-run (images are prebuilt by CI; nothing is built here).
# Prereqs: Docker, `docker login ghcr.io`, and a configured .env (see
# app/.env.prod.example and DEPLOY.md).
# The production stack is now GENERATED by `forge productionize` (C8) into the app dir
# (app/compose.prod.yaml) — the canonical stack `forge deploy` rolls. Do not hand-edit it.
# `forge deploy` (>=0.15.1) defaults --env-file to app/.env.prod (P10); these raw-compose helpers
# name the same file so `make deploy-config/ps/logs/down` resolve the prod secrets identically.
PROD := docker compose -f app/compose.prod.yaml --env-file app/.env.prod

# Deploy the current checkout — run ON THE BOX (release/deploy.sh git-pulls, then runs this
# over SSH). The ENTIRE deploy pipeline is now ONE platform capability — `forge release` (C18,
# forge >=0.23.0). It runs five ordered phases atomically + idempotently + fail-safe:
#   1. assess   (read-only)  resolve HEAD, compute the web ref `…/forge-os-app:sha-<commit>`,
#                            probe whether it's already published, read the current pin + host.
#   2. publish  (ci mode)    poll GHCR until publish-app.yml's build for `sha-<commit>` resolves a
#                            digest (bounded by --timeout/--poll-interval; retries transient errors).
#   3. repin                 `forge productionize --web-image <ref>@sha256:…` (keeps the data plane).
#   4. deploy                the C7 start-first roll + P14 drift gate + P16 tsx-- wrapper + P17
#                            fail-loud secret — forge-os.mardash.ai never loses its backend.
#   5. verify                the C14 post-deploy contract smoke against --host (the final gate).
# Fail-safe: any phase that throws STOPS before the next (never half-applied); a failed roll keeps
# the last-good replica serving; a red verify fails the release; a dirty tree is refused before any
# mutation. Re-running RESUMES from the first unsatisfied phase (a landed re-run is a no-op). This
# retires the ~10-step by-hand publish→wait→resolve→repin→deploy→verify flow — all inside one call.
#
# We pass `--env-file app/.env.prod` EXPLICITLY (P16 makes a relative --env-file safe): forge's
# default only passes it *when the file exists*, so on a box that still has a plain app/.env it would
# silently fall back to Compose's default (app/.env) — reading stale secrets. Passing it explicitly
# makes a missing app/.env.prod a LOUD error. The verify gate mirrors the C14 smoke contract: the two
# protected APIs 401, the cron path 403, `/` 302→/auth/login, /api/health is C6-shaped, the three auth
# methods are enabled, and POST /auth/refresh (no cookie) 401s.
deploy:
	$(MAKE) up          # ensure the control plane is running (idempotent; pulls control-plane image if missing)
	./forge release --app forge-os --host forge-os.mardash.ai \
	  --env-file app/.env.prod \
	  --health-path /api/health \
	  --api-path /api/goals --api-path /api/today \
	  --cron-path /api/cron/habits-finalize \
	  --page-path / \
	  --expect google,email,password-signup --check-refresh
	@$(PROD) ps
	@echo ""
	@echo "Released forge-os (assess→publish→repin→deploy→verify via forge release).  Public:  https://forge-os.mardash.ai/api/health"
	@echo "On the box:  make deploy-ps  /  make deploy-logs"

# `make release` is an alias for `make deploy` — the one-command pipeline is a "release" now.
release: deploy

deploy-ps:
	$(PROD) ps

deploy-logs:
	$(PROD) logs -f

# Validate app/compose.prod.yaml + the resolved app/.env.prod without touching anything.
deploy-config:
	$(PROD) config

# Stop the stack but KEEP the data volumes (postgres_data, forge_state).
# (Never `down -v` in prod — that destroys the database.)
deploy-down:
	$(PROD) down
