# Forge starter — convenience commands. These ONLY delegate to Docker.
# No local Node, npm, or build tools are assumed.

.PHONY: up down logs shell ps restart pull new-app \
        deploy deploy-ps deploy-logs deploy-config deploy-down

up:
	docker compose up -d
	@echo ""
	@echo "Forge is up. Provision a whole app in one command:"
	@echo "  ./new-app my-app                 # init->provision->install->build->test->lint"
	@echo "Or step by step: ./forge init app --name my-app  (then provision/install/build/…)"
	@echo "Or just tell Claude: \"build me a <thing>\" (see .claude/skills/provision-app)."

# One command to scaffold + validate a new app:  make new-app name=my-app
new-app:
	@test -n "$(name)" || (echo "usage: make new-app name=<kebab-name>"; exit 2)
	./new-app "$(name)"

down:
	docker compose down

logs:
	docker compose logs -f api

shell:
	docker compose exec api sh

ps:
	docker compose ps

restart:
	docker compose restart api

# Refresh the platform image from the registry.
pull:
	docker compose pull

# --- Production deployment (app/compose.prod.yaml — generated by C8) --------
# Runs on the DEPLOY host — the app + Forge data-plane sidecar + Postgres, no
# control plane. Pull-and-run (images are prebuilt by CI; nothing is built here).
# Prereqs: Docker, `docker login ghcr.io`, and a configured .env (see
# app/.env.prod.example and DEPLOY.md).
# The production stack is now GENERATED by `forge productionize` (C8) into the app dir
# (app/compose.prod.yaml) — the canonical stack `forge deploy` rolls. Do not hand-edit it.
PROD := docker compose -f app/compose.prod.yaml

# Deploy the current checkout — run ON THE BOX (release/deploy.sh git-pulls, then runs this
# over SSH). Zero-downtime is now a PLATFORM capability — `forge deploy` (C7): it reconciles
# postgres/data-plane in place, then rolls the public `web` service START-FIRST (new replica up
# and healthy, drained out of Traefik, before the old is removed), so forge-os.mardash.ai never
# loses its backend. We start the Forge control plane transiently to run it; it rolls the LOCAL
# prod stack over the Docker socket (no separate rollout script). Image pulls are non-fatal (the
# Docker-Desktop keychain can't be read over SSH — cached images still deploy); to land brand-new
# images, unlock the keychain + pull interactively first (see DEPLOY.md).
deploy:
	$(MAKE) up          # ensure the control plane is running (idempotent; pulls control-plane image if missing)
	# `forge deploy` (>=0.11.1) defaults --compose-file to the canonical stack `forge productionize`
	# emits, app/compose.prod.yaml — so no explicit --compose-file is needed (P7.2).
	./forge deploy --app forge-os --proxy-net proxy
	@$(PROD) ps
	@echo ""
	@echo "Deployed forge-os (zero-downtime roll via forge deploy).  Public:  https://forge-os.mardash.ai/api/health"
	@echo "On the box:  make deploy-ps  /  make deploy-logs"

deploy-ps:
	$(PROD) ps

deploy-logs:
	$(PROD) logs -f

# Validate app/compose.prod.yaml + the resolved .env without touching anything.
deploy-config:
	$(PROD) config

# Stop the stack but KEEP the data volumes (postgres_data, forge_state).
# (Never `down -v` in prod — that destroys the database.)
deploy-down:
	$(PROD) down
